# This is the headless service used by the StatefulSet to keep track of its replicas.
apiVersion: v1
kind: Service
metadata:
  name: tenant-security-proxy-sts
spec:
  ports:
    - port: 7777
      name: http
  clusterIP: None
  selector:
    app: tenant-security-proxy

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenant-security-proxy
spec:
  # We're not setting replicas here because that's controlled by a HorizontalPodAutoscaler.
  selector:
    matchLabels:
      app: tenant-security-proxy
  serviceName: tenant-security-proxy-sts
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: tenant-security-proxy
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '7777'
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-configmap: tsp-config
        vault.hashicorp.com/agent-pre-populate: "false"
        vault.hashicorp.com/ca-cert: /vault/tls/ca.crt
        vault.hashicorp.com/tls-secret: vault-tls
    spec:
      securityContext:
        runAsUser: 2 # Any non-root user will do.
        runAsGroup: 2
        fsGroup: 2
        runAsNonRoot: true
      serviceAccountName: tenant-security-proxy
      containers:
      - name: tenant-security-proxy
        image: tsp-placeholder
        command:
        - /app/godotenv
        - -o
        - -f
        - /vault/secrets/env
        - /app/tenant-security-proxy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: RUST_LOG
          value: info
        - name: IRONCORE_ENV
          value: stage
        - name: CB_OVERRIDE
          value: stage
        ports:
        - containerPort: 9000
          name: health
        - containerPort: 7777
          name: http
        readinessProbe:
          httpGet:
            path: /ready
            port: health
        securityContext:
          allowPrivilegeEscalation: false
        lifecycle:
          preStop:
            exec:
              command:
                - sleep
                - "10"
      - name: logdriver
        image: ld-placeholder
        command:
        - /app/godotenv
        - -o
        - -f
        - /vault/secrets/env
        - /app/tenant-security-logdriver
        resources:
          requests:
            cpu: 75m
            memory: 64Mi
        env:
        - name: CB_OVERRIDE
          value: stage
        - name: RUST_LOG
          value: info
        - name: IRONCORE_ENV
          value: stage
        ports:
        - containerPort: 9001
          name: health
        readinessProbe:
          httpGet:
            path: /ready
            port: health
        securityContext:
          allowPrivilegeEscalation: false
        lifecycle:
          preStop:
            exec:
              command:
                - sleep
                - "10"
        volumeMounts:
        - mountPath: /logdriver
          name: logdriver
  volumeClaimTemplates:
    - metadata:
        name: logdriver
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
