# The secrets needed by the TSP service.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: tenant-security-proxy
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cs-perf-test-tsp
    serviceAccount: tenant-security-proxy

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tenant-security-proxy-env
spec:
  vaultAuthRef: tenant-security-proxy
  mount: secret
  type: kv-v2
  path: cs-perf-test/tsp/ironcore-context
  destination:
    create: true
    overwrite: true
    name: tenant-security-proxy-ironcore-context
  rolloutRestartTargets:
  - kind: StatefulSet
    name: tenant-security-proxy

---

# The secrets for cloaked search.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloaked-search-proxy
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cs-perf-test-cs
    serviceAccount: cloaked-search

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloaked-search-proxy-perf-test-key
spec:
  vaultAuthRef: cloaked-search-proxy
  mount: secret
  type: kv-v2
  path: cs-perf-test/cloaked-search/perf-test-key
  destination:
    create: true
    overwrite: true
    name: cloaked-search-proxy-perf-test-key
    transformation:
      excludes:
      - .*
      templates:
        "perf-test.key":
          text: |
            {{- get .Secrets "perf-test.key" -}}
  rolloutRestartTargets:
  - kind: Deployment
    name: cloaked-search-v2

---
# The secrets needed by the cs-perf-test job
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cs-perf-test-runner
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cs-perf-test
    serviceAccount: cs-perf-test

---

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cs-perf-test-runner-env
spec:
  vaultAuthRef: cs-perf-test-runner
  mount: secret
  type: kv-v2
  path: cs-perf-test/cs-perf-test/env
  destination:
    create: true
    overwrite: true
    name: cs-perf-test-env
