apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cs-perf-test

resources:
- ../base

configMapGenerator:
- files:
  - config/cloaked-search/deploy.json
  - config/cloaked-search/indices/so.json
  - config/cloaked-search/indices/so500k.json
  name: cloaked-search-v2
