apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cs-perf-test

resources:
- ../cs-deploy.yaml
- ../cs-svc.yaml
- ../es-sts.yaml
- ../es-svc.yaml
- ../ns.yaml
- ../pvc.yaml
- ../sa.yaml
- ../secrets.yaml

configMapGenerator:
- files:
  - ../run.sh
  - ../../run-500k.sh
  - ../../queries/the-title
  - ../../queries/the-title-prefix
  name: cs-perf-app
  options:
    disableNameSuffixHash: true
- files:
  - ../config/elastic-search/elasticsearch.yml
  name: elasticsearch
- files:
  - config/cloaked-search/deploy.json
  - config/cloaked-search/indices/so.json
  - config/cloaked-search/indices/so500k.json
  name: cloaked-search-v2

# The version of cs-perf-test (elastic/rally) is specified directly in the cs-perf-test.yaml file, because it's loaded separately.
images:
- name: cloaked-search-placeholder
  newName: gcr.io/ironcore-images/cloaked-search
  newTag: 2.8.0
- name: elasticsearch-placeholder
  newName: elasticsearch
  newTag: 8.5.0
- name: tsp-placeholder
  newName: gcr.io/ironcore-images/tenant-security-proxy
  newTag: 4.13.0
